

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>London Bytes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>
          <Image
          className="image" 
          src="/uncles_1.png"
          width={525}
          height={525}
          alt="Three Uncles beef noodles"
          />
          <p>
            Restaurant Review App homepage
            <br>
            </br>
            London Bytes
          </p>

        </main>
      </div>
    </>
  );
}
